dev:
    :google_base_url: https://www.google.com
    :amtrak_base_url: https://www.amtrak.com

qa:
    :google_base_url: https://www.google.com
    :amtrak_base_url: https://www.amtrak.com

prod:
    :google_base_url: https://www.google.com
    :amtrak_base_url: https://www.amtrak.com
